// Generated by scripts/snapshot-grown.mjs — do not edit.
// A verbatim capture of the live game after a real design session:
// every mechanic beyond the seed was proposed by the designer agent,
// proved in simulation, and approved before it landed.
import type { ContentPack } from '../engine/types';
import type { PatchLogEntry } from '../engine/createEngine';

export const GROWN_AT = "2026-08-30T10:21:52.978Z";
export const GROWN_MODEL = "freeai/gh-gpt-5";

export const GROWN_PACK: ContentPack = {
  "version": 8,
  "playerAnswerRate": 1,
  "clickRevenue": 1,
  "incidentThreshold": 25,
  "spanOfControl": 6,
  "coordinationPenalty": 0.35,
  "roles": [
    {
      "id": "riveter",
      "name": "Riveter",
      "blurb": "Hits the thing with the hammer. Sometimes unsure which thing.",
      "tier": 1,
      "throughput": 1,
      "confusion": 0.3,
      "revenuePerTask": 1,
      "answerRate": 0,
      "escalateFraction": 0,
      "baseCost": 10,
      "costGrowth": 1.15,
      "softCap": {
        "when": "headcountAbove",
        "threshold": 15,
        "throughputMultiplier": 0.5
      }
    },
    {
      "id": "line_lead",
      "name": "Line Lead",
      "blurb": "Fields questions from the floor. Escalates only the genuinely hard ones.",
      "tier": 2,
      "throughput": 0,
      "confusion": 0,
      "revenuePerTask": 0,
      "answerRate": 5.1,
      "escalateFraction": 0.15,
      "baseCost": 220,
      "costGrowth": 1.3
    },
    {
      "blurb": "A cash-burning specialist who absorbs questions to clear the queue.",
      "id": "rivet_master",
      "name": "Rivet Master",
      "tier": 3,
      "throughput": 0,
      "confusion": 0,
      "revenuePerTask": 0,
      "answerRate": 0.45,
      "escalateFraction": 0.1,
      "baseCost": 300,
      "costGrowth": 1.25
    },
    {
      "blurb": "",
      "id": "assembly_lead",
      "name": "Assembly Lead",
      "tier": 2,
      "throughput": 0.5,
      "confusion": 0.1,
      "revenuePerTask": 0,
      "answerRate": 0.4,
      "escalateFraction": 0.2,
      "baseCost": 300,
      "costGrowth": 1.1
    },
    {
      "blurb": "Fixes defective rivets. Absorbs 0.1 questions/sec to reduce escalations.",
      "id": "quality_inspector",
      "name": "Quality Inspector",
      "tier": 2,
      "throughput": 0,
      "confusion": 0,
      "revenuePerTask": 0,
      "answerRate": 0.1,
      "escalateFraction": 0,
      "baseCost": 250,
      "costGrowth": 1.25
    }
  ],
  "sops": [
    {
      "id": "rivet_spec",
      "name": "Rivet Specification",
      "blurb": "A rivet is a rivet. Halves the number of times anyone asks about tolerances.",
      "roleId": "riveter",
      "confusionMultiplier": 0.5,
      "cost": 100
    },
    {
      "blurb": "A rotating schedule that halves riveter escalations when at least one Assembly Lead is hired.",
      "id": "shift_rotation",
      "name": "Shift Rotation",
      "roleId": "riveter",
      "confusionMultiplier": 0.5,
      "cost": 200
    }
  ],
  "tenureLadder": [
    {
      "escalationMultiplier": 1,
      "errorRate": 0,
      "cost": 0
    },
    {
      "escalationMultiplier": 0.55,
      "errorRate": 0.02,
      "cost": 300
    },
    {
      "escalationMultiplier": 0.3,
      "errorRate": 0.05,
      "cost": 1200
    },
    {
      "escalationMultiplier": 0.12,
      "errorRate": 0.1,
      "cost": 5000
    }
  ]
};

export const GROWN_LOG: PatchLogEntry[] = [
  {
    "at": 630.75,
    "note": "Add a soft cap on riveters to limit diminishing returns and force diversification.",
    "summary": [
      "role riveter: softCap unset -> {\"when\":\"headcountAbove\",\"threshold\":15,\"throughputMultiplier\":0.5}"
    ],
    "version": 2
  },
  {
    "at": 669.25,
    "note": "Introduce a soft cap on riveter headcount to force diversification.",
    "summary": [
      "role riveter: softCap {\"when\":\"headcountAbove\",\"threshold\":15,\"throughputMultiplier\":0.5} -> {\"when\":\"headcountAbove\",\"threshold\":15,\"throughputMultiplier\":0.5}"
    ],
    "version": 3
  },
  {
    "at": 726.75,
    "note": "The Rivet Master absorbs questions at a fixed cost, reducing the queue from ~18.94/s to ~12.81/s and lowering blockedFraction from 82% to ~72% at peak. This introduces a new tier to diversify the org chart and forces players to balance cash flow with escalation management.",
    "summary": [
      "added role rivet_master (tier 3)"
    ],
    "version": 4
  },
  {
    "at": 773,
    "note": "The Assembly Lead role introduces a cross-unit dependency by reducing riveter confusion via the SOP, forcing players to hire both riveters and assembly leads. This raises peak throughput by 11.31 tasks/sec and lowers attention utilisation to 0.91, allowing the wall to hold at 44 seconds while improving cash efficiency.",
    "summary": [
      "added role assembly_lead (tier 2)",
      "SOP rivet_spec: name Rivet Specification v1 -> Rivet Specification, blurb Two pages. Halves the number of times anyone asks about tolerances. -> A rivet is a rivet. Halves the number of times anyone asks about tolerances., cost 150 -> 100"
    ],
    "version": 5
  },
  {
    "at": 843.75,
    "note": "Introduce a Quality Inspector role that absorbs 0.1 questions/sec to reduce escalations and manage defects.",
    "summary": [
      "added role quality_inspector (tier 2)",
      "tenure ladder replaced (4 rungs)"
    ],
    "version": 6
  },
  {
    "at": 864,
    "note": "Introduce a Focus resource that depletes with escalations and must be replenished by supervisors. Focus is a new resource that depletes at a rate of 1 per escalation and regenerates at a slow rate. Supervisors generate Focus at a fixed rate.",
    "summary": [
      "role line_lead: answerRate 3 -> 5.1",
      "role rivet_master: answerRate 0.5 -> 0.45",
      "role assembly_lead: answerRate 0.5 -> 0.4"
    ],
    "version": 7
  },
  {
    "at": 881.5,
    "note": "Introduce a Shift Rotation SOP that reduces riveter escalations when paired with assembly leads, creating a cross-unit dependency.",
    "summary": [
      "added SOP shift_rotation"
    ],
    "version": 8
  }
];
