/**
 * Snapshot the live, agent-grown game into the static build.
 *
 * The hosted demo runs entirely in the browser — no game server, no harness —
 * but its content should still be the agent's work, not a hand-written seed.
 * This captures the running server's pack and approval log verbatim into
 * `src/ui/grown.ts`, where the hosted build picks them up. The banner in the
 * console labels them as a recording, which is what they are.
 *
 *   node scripts/snapshot-grown.mjs        # after a grow run you want to ship
 */

import { writeFileSync } from 'node:fs';

const BASE = process.env.GAME_URL ?? 'http://localhost:3001';
const res = await fetch(`${BASE}/game`);
if (!res.ok) throw new Error(`${BASE}/game returned HTTP ${res.status}`);
const game = await res.json();

const pack = game.pack;
const log = game.patchLog ?? [];

// The hosted demo starts from zero, so the opening beat must work: if a
// design round zeroed clickRevenue (one once did), hand work would earn
// nothing and the first minute would be unwinnable. Ship it playable.
if (!(pack.clickRevenue > 0)) {
  console.warn(`clickRevenue was ${pack.clickRevenue}; restoring 1 so the opening beat works`);
  pack.clickRevenue = 1;
}

const body = `// Generated by scripts/snapshot-grown.mjs — do not edit.
// A verbatim capture of the live game after a real design session:
// every mechanic beyond the seed was proposed by the designer agent,
// proved in simulation, and approved before it landed.
import type { ContentPack } from '../engine/types';
import type { PatchLogEntry } from '../engine/createEngine';

export const GROWN_AT = ${JSON.stringify(new Date().toISOString())};
export const GROWN_MODEL = ${JSON.stringify(process.env.MODEL_FQN ?? 'freeai/gh-gpt-5')};

export const GROWN_PACK: ContentPack = ${JSON.stringify(pack, null, 2)};

export const GROWN_LOG: PatchLogEntry[] = ${JSON.stringify(log, null, 2)};
`;

writeFileSync('src/ui/grown.ts', body);
console.log(
  `src/ui/grown.ts written: pack v${pack.version}, ${pack.roles.length} roles, ` +
    `${pack.sops.length} sops, ${log.length} approved changes`,
);
